import QuaternionicSymmetry.CompactSymplecticProjectorFirstBlockRowAction

/-! Every actual first Sp(1)-block derivative lies in the four-dimensional
real quaternion algebra generated by the checked base-tangent I and J. -/

namespace QuaternionicSymmetry.CompactSymplecticProjectorFirstBlockSpan

open Manifold
open CompactSymplecticProjectorBaseTangent
open CompactSymplecticProjectorBaseTangentRange
open CompactSymplecticProjectorBaseQuaternionic
open CompactSymplecticProjectorIsotropyUnits
open CompactSymplecticProjectorFirstBlockRowAction
open CompactSymplecticStabilizerBlockPair
open CompactSymplecticClosedSubgroupSource
open CompactSymplecticHomogeneousAtlasSource
open scoped Matrix.Norms.Operator Manifold ContDiff
noncomputable section
set_option maxHeartbeats 1000000

private abbrev RModel (d : ℕ) := Fin d → ℝ

private theorem complex_decompose (a b x y : ℂ) :
    a * x - b * y =
      (a.re : ℂ) * x + (a.im : ℂ) * (Complex.I * x) -
        (b.re : ℂ) * y - (b.im : ℂ) * (Complex.I * y) := by
  calc
    a * x - b * y =
      ((a.re : ℂ) + a.im * Complex.I) * x -
        ((b.re : ℂ) + b.im * Complex.I) * y := by
          rw [Complex.re_add_im, Complex.re_add_im]
    _ = _ := by ring

private theorem complex_decompose_add (a b x y : ℂ) :
    a * x + b * y =
      (a.re : ℂ) * x + (a.im : ℂ) * (Complex.I * x) +
        (b.re : ℂ) * y + (b.im : ℂ) * (Complex.I * y) := by
  calc
    a * x + b * y =
      ((a.re : ℂ) + a.im * Complex.I) * x +
        ((b.re : ℂ) + b.im * Complex.I) * y := by
          rw [Complex.re_add_im, Complex.re_add_im]
    _ = _ := by ring

private theorem euclideanCoord
    (hDesc : GeneralSmoothMapSource.LeeSurjectiveSubmersionDescentTheorem)
    (hImm : GeneralSmoothMapSource.LeeEquivariantImmersionTheorem)
    (n d e q : ℕ) (g : EmbeddedRealLieAtlas n d)
    (atlas : SmoothHomogeneousAtlas n d e q g) (hq : q = 4 * n) :
    letI := atlas.quotientCharts
    ∀ (v : TangentSpace 𝓘(ℝ, RModel q) (baseCoset n))
      (c : Fin n ⊕ Fin n),
      baseTangentEuclideanEquiv hDesc hImm n d e q g atlas hq v c =
        ((baseTangentUpperLinear hDesc n d e q g atlas) v).1 0 c := by
  letI := atlas.quotientCharts
  intro v c
  rfl

/-- Every actual first-block isotropy derivative is a real quaternionic
linear combination of identity and the three genuine tangent operators. -/
theorem firstBlock_derivative_quaternion_span
    (hDesc : GeneralSmoothMapSource.LeeSurjectiveSubmersionDescentTheorem)
    (hImm : GeneralSmoothMapSource.LeeEquivariantImmersionTheorem)
    (n d e q : ℕ) (g : EmbeddedRealLieAtlas n d)
    (atlas : SmoothHomogeneousAtlas n d e q g) (hq : q = 4 * n)
    (A : FirstBlockGroup) :
    letI := atlas.quotientCharts
    ∀ v : TangentSpace 𝓘(ℝ, RModel q) (baseCoset n),
      mfderiv 𝓘(ℝ, RModel q) 𝓘(ℝ, RModel q)
        (leftCosetAction n (firstBlockLift n A).1) (baseCoset n) v =
      (A.1.1 0 0).re • v + (A.1.1 0 0).im •
        baseI hDesc hImm n d e q g atlas hq v -
      (A.1.1 0 1).re • baseJ hDesc hImm n d e q g atlas hq v -
      (A.1.1 0 1).im • baseK hDesc hImm n d e q g atlas hq v := by
  letI := atlas.quotientCharts
  intro v
  let E := baseTangentEuclideanEquiv hDesc hImm n d e q g atlas hq
  have hI (w) : E (baseI hDesc hImm n d e q g atlas hq w) =
      QuaternionicMatrixModel.standardI n (E w) := by
    simp [E, baseI, baseTangentEuclideanEquiv]
  have hJ (w) : E (baseJ hDesc hImm n d e q g atlas hq w) =
      QuaternionicMatrixModel.standardJ n (E w) := by
    simp [E, baseJ, baseTangentEuclideanEquiv]
  have hK (w) : E (baseK hDesc hImm n d e q g atlas hq w) =
      QuaternionicMatrixModel.standardI n
        (QuaternionicMatrixModel.standardJ n (E w)) := by
    change E (baseI hDesc hImm n d e q g atlas hq
      (baseJ hDesc hImm n d e q g atlas hq w)) = _
    rw [hI, hJ]
  apply E.injective
  ext c
  simp only [map_add, map_sub, map_smul, hI, hJ, hK]
  rcases c with j | j
  · simp only [QuaternionicMatrixModel.standardI_apply]
    simp [QuaternionicMatrixModel.standardJ_apply_inl, smul_eq_mul]
    rw [euclideanCoord hDesc hImm n d e q g atlas hq]
    rw [euclideanCoord hDesc hImm n d e q g atlas hq]
    rw [euclideanCoord hDesc hImm n d e q g atlas hq]
    exact (firstBlock_tangent_row_inl hDesc n d e q g atlas A v j).trans
      (complex_decompose _ _ _ _)
  · simp only [QuaternionicMatrixModel.standardI_apply]
    simp [QuaternionicMatrixModel.standardJ_apply_inr, smul_eq_mul]
    rw [euclideanCoord hDesc hImm n d e q g atlas hq]
    rw [euclideanCoord hDesc hImm n d e q g atlas hq]
    rw [euclideanCoord hDesc hImm n d e q g atlas hq]
    exact (firstBlock_tangent_row_inr hDesc n d e q g atlas A v j).trans
      (complex_decompose_add _ _ _ _)

end
end QuaternionicSymmetry.CompactSymplecticProjectorFirstBlockSpan
