import QuaternionicSymmetry.ComplexProjectiveActualConeProjCoordinates
import Mathlib.RingTheory.MvPolynomial.Ideal

/-! Every positive-degree element of the actual cone quotient belongs
to the ideal generated by the coordinate classes. This is the algebraic
input for the standard coordinate opens to cover its literal `Proj`. -/

namespace QuaternionicSymmetry.ComplexProjectiveActualConeProjCoordinateIdeal

open ComplexProjectiveTopology
open ComplexProjectiveDiagonalVanishingIdeal
open ComplexProjectiveConeQuotientHomogeneousPieces
open ComplexProjectiveActualConeProjCoordinates
noncomputable section

variable {d : ℕ}

def coordinateIdeal (A : Set (Space d)) :
    Ideal (MvPolynomial (Fin (d + 1)) ℂ ⧸ vanishingIdeal A) :=
  Ideal.span (Set.range (coordinateClass A))

theorem map_idealOfVars_eq_coordinateIdeal (A : Set (Space d)) :
    (MvPolynomial.idealOfVars (Fin (d + 1)) ℂ).map
        (Ideal.Quotient.mk (vanishingIdeal A)) = coordinateIdeal A := by
  simp only [MvPolynomial.idealOfVars, coordinateIdeal, Ideal.map_span]
  congr 1
  ext q
  simp [Set.mem_image, Set.mem_range, coordinateClass]

theorem homogeneous_mem_idealOfVars_of_pos
    {n : ℕ} (hn : 0 < n)
    {p : MvPolynomial (Fin (d + 1)) ℂ}
    (hp : p.IsHomogeneous n) :
    p ∈ MvPolynomial.idealOfVars (Fin (d + 1)) ℂ := by
  have hsupport : ∀ m ∈ p.support, 1 ≤ m.degree := by
    intro m hm
    have hdegree : m.degree = n := by
      by_contra hne
      exact (Finsupp.mem_support_iff.mp hm) (hp.coeff_eq_zero hne)
    omega
  simpa only [pow_one] using
    (MvPolynomial.mem_pow_idealOfVars_iff 1 p).2 hsupport

theorem quotientPiece_positive_le_coordinateIdeal
    (A : Set (Space d)) {n : ℕ} (hn : 0 < n) :
    (quotientPiece A n : Submodule ℂ
      (MvPolynomial (Fin (d + 1)) ℂ ⧸ vanishingIdeal A)) ≤
        (coordinateIdeal A).restrictScalars ℂ := by
  intro q hq
  obtain ⟨p, hp, rfl⟩ := (mem_quotientPiece_iff A n q).mp hq
  change Ideal.Quotient.mk (vanishingIdeal A) p ∈ coordinateIdeal A
  rw [← map_idealOfVars_eq_coordinateIdeal]
  exact Ideal.mem_map_of_mem _ (homogeneous_mem_idealOfVars_of_pos hn hp)

end
end QuaternionicSymmetry.ComplexProjectiveActualConeProjCoordinateIdeal
