import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Algebra.Algebra.Rat
import Mathlib.Tactic

/-! The commutative algebra generated by two-forms in an actual exterior algebra.

No commutativity hypothesis is imposed on the ambient exterior algebra. It follows
for the subalgebra below from its defining exterior relations. Every homogeneous
element of even degree belongs to this subalgebra.
-/

namespace QuaternionicSymmetry.EvenForms

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

private theorem generator_swap (x y : M) :
    ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y =
      -(ExteriorAlgebra.ι R y * ExteriorAlgebra.ι R x) :=
  eq_neg_of_add_eq_zero_left (ExteriorAlgebra.ι_add_mul_swap x y)

/-- A product of two exterior generators commutes with each generator. -/
theorem pair_commutes_generator (x y z : M) :
    Commute (ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y) (ExteriorAlgebra.ι R z) := by
  change (ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y) * ExteriorAlgebra.ι R z = _
  calc
    _ = ExteriorAlgebra.ι R x * (ExteriorAlgebra.ι R y * ExteriorAlgebra.ι R z) :=
      mul_assoc _ _ _
    _ = ExteriorAlgebra.ι R x * -(ExteriorAlgebra.ι R z * ExteriorAlgebra.ι R y) := by
      rw [generator_swap y z]
    _ = -(ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R z) * ExteriorAlgebra.ι R y := by
      noncomm_ring
    _ = -(-(ExteriorAlgebra.ι R z * ExteriorAlgebra.ι R x)) * ExteriorAlgebra.ι R y := by
      rw [generator_swap x z]
    _ = ExteriorAlgebra.ι R z * (ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y) := by
      noncomm_ring

/-- Decomposable two-forms commute with one another. -/
theorem pairs_commute (x y z w : M) :
    Commute (ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y)
      (ExteriorAlgebra.ι R z * ExteriorAlgebra.ι R w) :=
  (pair_commutes_generator x y z).mul_right (pair_commutes_generator x y w)

/-- The algebra of even exterior expressions, generated by decomposable two-forms. -/
def evenSubalgebra (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] :
    Subalgebra R (ExteriorAlgebra R M) :=
  Algebra.adjoin R {a | ∃ x y : M, a = ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y}

instance : CommRing (evenSubalgebra R M) :=
  Algebra.adjoinCommRingOfComm R (by
    rintro a ⟨x, y, rfl⟩ b ⟨z, w, rfl⟩
    exact (pairs_commute x y z w).eq)

/-- Rational polynomial coefficients act through the coefficient ring. -/
instance [Algebra ℚ R] : Algebra ℚ (evenSubalgebra R M) :=
  Algebra.compHom (evenSubalgebra R M) (algebraMap ℚ R)

theorem pair_mem (x y : M) :
    ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y ∈ evenSubalgebra R M :=
  Algebra.subset_adjoin ⟨x, y, rfl⟩

theorem even_product_mem (n : ℕ) (v : Fin (2 * n) → M) :
    ExteriorAlgebra.ιMulti R (2 * n) v ∈ evenSubalgebra R M := by
  induction n with
  | zero => simp
  | succ n ih =>
    change ExteriorAlgebra.ιMulti R (2 * n + 2) v ∈ evenSubalgebra R M
    rw [ExteriorAlgebra.ιMulti_succ_apply, ExteriorAlgebra.ιMulti_succ_apply, ← mul_assoc]
    exact (evenSubalgebra R M).mul_mem (pair_mem _ _) (ih _)

/-- All homogeneous forms of degree `2 * n` belong to the commutative algebra. -/
theorem even_degree_le (n : ℕ) :
    ExteriorAlgebra.exteriorPower R (2 * n) M ≤ (evenSubalgebra R M).toSubmodule := by
  rw [← ExteriorAlgebra.ιMulti_span_fixedDegree]
  apply Submodule.span_le.mpr
  rintro _ ⟨v, rfl⟩
  exact even_product_mem n v

/-- Two-forms as elements of the commutative algebra, with no extra hypotheses. -/
def ofTwoForm (a : ExteriorAlgebra.exteriorPower R 2 M) : evenSubalgebra R M :=
  ⟨a, even_degree_le 1 a.property⟩

@[simp] theorem ofTwoForm_coe (a : ExteriorAlgebra.exteriorPower R 2 M) :
    (ofTwoForm a : ExteriorAlgebra R M) = a := rfl

end QuaternionicSymmetry.EvenForms
