import QuaternionicSymmetry.EvenForms
import Mathlib.Tactic

/-! Functoriality of the algebra generated by even exterior expressions. -/

namespace QuaternionicSymmetry.EvenForms

noncomputable section

variable {R M N : Type*} [CommRing R] [AddCommGroup M] [Module R M]
  [AddCommGroup N] [Module R N]

private theorem map_mem_even (f : M →ₗ[R] N) {x : ExteriorAlgebra R M}
    (hx : x ∈ evenSubalgebra R M) :
    ExteriorAlgebra.map f x ∈ evenSubalgebra R N := by
  induction hx using Algebra.adjoin_induction with
  | mem x hx =>
      rcases hx with ⟨u, v, rfl⟩
      simpa only [map_mul, ExteriorAlgebra.map_apply_ι] using
        pair_mem (f u) (f v)
  | algebraMap r =>
      simp
  | add x y hx hy hxm hym =>
      simpa only [map_add] using (evenSubalgebra R N).add_mem hxm hym
  | mul x y hx hy hxm hym =>
      simpa only [map_mul] using (evenSubalgebra R N).mul_mem hxm hym

/-- The exterior algebra map induced by a linear map restricts to the
commutative algebra generated by decomposable two-forms. -/
def map (f : M →ₗ[R] N) :
    evenSubalgebra R M →ₐ[R] evenSubalgebra R N where
  toFun x := ⟨ExteriorAlgebra.map f x, map_mem_even f x.property⟩
  map_one' := by
    ext
    simp
  map_mul' x y := by
    ext
    simp
  map_zero' := by
    ext
    simp
  map_add' x y := by
    ext
    simp
  commutes' r := by
    ext
    simp

@[simp] theorem map_apply_coe (f : M →ₗ[R] N) (x : evenSubalgebra R M) :
    ((map f x : evenSubalgebra R N) : ExteriorAlgebra R N) =
      ExteriorAlgebra.map f (x : ExteriorAlgebra R M) := rfl

theorem map_pair (f : M →ₗ[R] N) (x y : M) :
    map f (⟨ExteriorAlgebra.ι R x * ExteriorAlgebra.ι R y, pair_mem x y⟩) =
      ⟨ExteriorAlgebra.ι R (f x) * ExteriorAlgebra.ι R (f y), pair_mem (f x) (f y)⟩ := by
  ext
  simp [map]

end
end QuaternionicSymmetry.EvenForms
