import QuaternionicSymmetry.H2WitnessThirteen
import QuaternionicSymmetry.FiniteVirtualDensity

/-! Generated by scripts/generate_killing_fields_route.py from the paper's
rank-14 twelve-profile certificate. Every displayed identity is kernel checked.
Existing certificates and theorems are left unchanged. -/
namespace QuaternionicSymmetry.KillingFieldsPaperCertificate
open MvPolynomial
open DimensionThirteenFourteenDensity
noncomputable section
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option maxHeartbeats 8000000

def reduced2 : P :=
  C (16 : ℚ)

def reduced3 : P :=
  C (32 : ℚ) * u
    + C (8 / 3 : ℚ) * p1

def reduced4 : P :=
  C (48 : ℚ) * u
    + C (16 / 3 : ℚ) * p1

def reduced5 : P :=
  C (72 : ℚ) * u ^ 2
    + C (536 / 45 : ℚ) * u * p1
    + C (4 / 45 : ℚ) * p2
    + C (4 / 9 : ℚ) * p1 ^ 2

def reduced6 : P :=
  C (96 : ℚ) * u ^ 2
    + C (832 / 45 : ℚ) * u * p1
    + C (8 / 45 : ℚ) * p2
    + C (8 / 9 : ℚ) * p1 ^ 2

def reduced7 : P :=
  C (128 : ℚ) * u ^ 3
    + C (208 / 7 : ℚ) * u ^ 2 * p1
    + C (368 / 945 : ℚ) * u * p2
    + C (296 / 135 : ℚ) * u * p1 ^ 2
    + C (16 / 2835 : ℚ) * p3
    + C (4 / 135 : ℚ) * p1 * p2
    + C (4 / 81 : ℚ) * p1 ^ 3

def reduced8 : P :=
  C (160 : ℚ) * u ^ 3
    + C (12896 / 315 : ℚ) * u ^ 2 * p1
    + C (568 / 945 : ℚ) * u * p2
    + C (472 / 135 : ℚ) * u * p1 ^ 2
    + C (32 / 2835 : ℚ) * p3
    + C (8 / 135 : ℚ) * p1 * p2
    + C (8 / 81 : ℚ) * p1 ^ 3

def reduced9 : P :=
  C (200 : ℚ) * u ^ 4
    + C (90256 / 1575 : ℚ) * u ^ 3 * p1
    + C (4376 / 4725 : ℚ) * u ^ 2 * p2
    + C (85072 / 14175 : ℚ) * u ^ 2 * p1 ^ 2
    + C (104 / 4725 : ℚ) * u * p3
    + C (2036 / 14175 : ℚ) * u * p1 * p2
    + C (4 / 15 : ℚ) * u * p1 ^ 3
    + C (2 / 4725 : ℚ) * p4
    + C (16 / 8505 : ℚ) * p1 * p3
    + C (1 / 2025 : ℚ) * p2 ^ 2
    + C (2 / 405 : ℚ) * p1 ^ 2 * p2
    + C (1 / 243 : ℚ) * p1 ^ 4

def reduced10 : P :=
  C (240 : ℚ) * u ^ 4
    + C (16576 / 225 : ℚ) * u ^ 3 * p1
    + C (5912 / 4725 : ℚ) * u ^ 2 * p2
    + C (120584 / 14175 : ℚ) * u ^ 2 * p1 ^ 2
    + C (464 / 14175 : ℚ) * u * p3
    + C (3232 / 14175 : ℚ) * u * p1 * p2
    + C (176 / 405 : ℚ) * u * p1 ^ 3
    + C (4 / 4725 : ℚ) * p4
    + C (32 / 8505 : ℚ) * p1 * p3
    + C (2 / 2025 : ℚ) * p2 ^ 2
    + C (4 / 405 : ℚ) * p1 ^ 2 * p2
    + C (2 / 243 : ℚ) * p1 ^ 4

def reduced11 : P :=
  C (288 : ℚ) * u ^ 5
    + C (4965304 / 51975 : ℚ) * u ^ 4 * p1
    + C (154736 / 93555 : ℚ) * u ^ 3 * p2
    + C (35416 / 2835 : ℚ) * u ^ 3 * p1 ^ 2
    + C (18848 / 467775 : ℚ) * u ^ 2 * p3
    + C (16052 / 42525 : ℚ) * u ^ 2 * p1 * p2
    + C (33772 / 42525 : ℚ) * u ^ 2 * p1 ^ 3
    + C (8 / 6237 : ℚ) * u * p4
    + C (1048 / 127575 : ℚ) * u * p1 * p3
    + C (4 / 1701 : ℚ) * u * p2 ^ 2
    + C (124 / 4725 : ℚ) * u * p1 ^ 2 * p2
    + C (88 / 3645 : ℚ) * u * p1 ^ 4
    + C (16 / 467775 : ℚ) * p5
    + C (2 / 14175 : ℚ) * p1 * p4
    + C (8 / 127575 : ℚ) * p2 * p3
    + C (8 / 25515 : ℚ) * p1 ^ 2 * p3
    + C (1 / 6075 : ℚ) * p1 * p2 ^ 2
    + C (2 / 3645 : ℚ) * p1 ^ 3 * p2
    + C (1 / 3645 : ℚ) * p1 ^ 5

def reduced12 : P :=
  C (336 : ℚ) * u ^ 5
    + C (6101552 / 51975 : ℚ) * u ^ 4 * p1
    + C (962072 / 467775 : ℚ) * u ^ 3 * p2
    + C (33368 / 2025 : ℚ) * u ^ 3 * p1 ^ 2
    + C (22384 / 467775 : ℚ) * u ^ 2 * p3
    + C (22408 / 42525 : ℚ) * u ^ 2 * p1 * p2
    + C (49064 / 42525 : ℚ) * u ^ 2 * p1 ^ 3
    + C (268 / 155925 : ℚ) * u * p4
    + C (1616 / 127575 : ℚ) * u * p1 * p3
    + C (158 / 42525 : ℚ) * u * p2 ^ 2
    + C (604 / 14175 : ℚ) * u * p1 ^ 2 * p2
    + C (146 / 3645 : ℚ) * u * p1 ^ 4
    + C (32 / 467775 : ℚ) * p5
    + C (4 / 14175 : ℚ) * p1 * p4
    + C (16 / 127575 : ℚ) * p2 * p3
    + C (16 / 25515 : ℚ) * p1 ^ 2 * p3
    + C (2 / 6075 : ℚ) * p1 * p2 ^ 2
    + C (4 / 3645 : ℚ) * p1 ^ 3 * p2
    + C (2 / 3645 : ℚ) * p1 ^ 5

def reduced13 : P :=
  C (392 : ℚ) * u ^ 6
    + C (45727288 / 315315 : ℚ) * u ^ 5 * p1
    + C (1781548 / 716625 : ℚ) * u ^ 4 * p2
    + C (121006364 / 5457375 : ℚ) * u ^ 4 * p1 ^ 2
    + C (1323256 / 34827975 : ℚ) * u ^ 3 * p3
    + C (36184556 / 49116375 : ℚ) * u ^ 3 * p1 * p2
    + C (3397924 / 1913625 : ℚ) * u ^ 3 * p1 ^ 3
    + C (8894 / 19348875 : ℚ) * u ^ 2 * p4
    + C (284456 / 16372125 : ℚ) * u ^ 2 * p1 * p3
    + C (26423 / 4465125 : ℚ) * u ^ 2 * p2 ^ 2
    + C (16042 / 212625 : ℚ) * u ^ 2 * p1 ^ 2 * p2
    + C (9911 / 127575 : ℚ) * u ^ 2 * p1 ^ 4
    + C (1168 / 19348875 : ℚ) * u * p5
    + C (1154 / 2338875 : ℚ) * u * p1 * p4
    + C (3596 / 13395375 : ℚ) * u * p2 * p3
    + C (116 / 76545 : ℚ) * u * p1 ^ 2 * p3
    + C (61 / 70875 : ℚ) * u * p1 * p2 ^ 2
    + C (1214 / 382725 : ℚ) * u * p1 ^ 3 * p2
    + C (19 / 10935 : ℚ) * u * p1 ^ 5
    + C (5528 / 1915538625 : ℚ) * p6
    + C (16 / 1403325 : ℚ) * p1 * p5
    + C (1 / 212625 : ℚ) * p2 * p4
    + C (1 / 42525 : ℚ) * p1 ^ 2 * p4
    + C (16 / 8037225 : ℚ) * p3 ^ 2
    + C (8 / 382725 : ℚ) * p1 * p2 * p3
    + C (8 / 229635 : ℚ) * p1 ^ 3 * p3
    + C (1 / 546750 : ℚ) * p2 ^ 3
    + C (1 / 36450 : ℚ) * p1 ^ 2 * p2 ^ 2
    + C (1 / 21870 : ℚ) * p1 ^ 4 * p2
    + C (1 / 65610 : ℚ) * p1 ^ 6

def reduced14 : P :=
  C (448 : ℚ) * u ^ 6
    + C (816577408 / 4729725 : ℚ) * u ^ 5 * p1
    + C (620496752 / 212837625 : ℚ) * u ^ 4 * p2
    + C (152085968 / 5457375 : ℚ) * u ^ 4 * p1 ^ 2
    + C (10779136 / 383107725 : ℚ) * u ^ 3 * p3
    + C (46487872 / 49116375 : ℚ) * u ^ 3 * p1 * p2
    + C (655424 / 273375 : ℚ) * u ^ 3 * p1 ^ 3
    + C (-170152 / 212837625 : ℚ) * u ^ 2 * p4
    + C (1084576 / 49116375 : ℚ) * u ^ 2 * p1 * p3
    + C (36256 / 4465125 : ℚ) * u ^ 2 * p2 ^ 2
    + C (23024 / 212625 : ℚ) * u ^ 2 * p1 ^ 2 * p2
    + C (4904 / 42525 : ℚ) * u ^ 2 * p1 ^ 4
    + C (3712 / 70945875 : ℚ) * u * p5
    + C (1648 / 2338875 : ℚ) * u * p1 * p4
    + C (5512 / 13395375 : ℚ) * u * p2 * p3
    + C (184 / 76545 : ℚ) * u * p1 ^ 2 * p3
    + C (296 / 212625 : ℚ) * u * p1 * p2 ^ 2
    + C (2008 / 382725 : ℚ) * u * p1 ^ 3 * p2
    + C (32 / 10935 : ℚ) * u * p1 ^ 5
    + C (11056 / 1915538625 : ℚ) * p6
    + C (32 / 1403325 : ℚ) * p1 * p5
    + C (2 / 212625 : ℚ) * p2 * p4
    + C (2 / 42525 : ℚ) * p1 ^ 2 * p4
    + C (32 / 8037225 : ℚ) * p3 ^ 2
    + C (16 / 382725 : ℚ) * p1 * p2 * p3
    + C (16 / 229635 : ℚ) * p1 ^ 3 * p3
    + C (1 / 273375 : ℚ) * p2 ^ 3
    + C (1 / 18225 : ℚ) * p1 ^ 2 * p2 ^ 2
    + C (1 / 10935 : ℚ) * p1 ^ 4 * p2
    + C (1 / 32805 : ℚ) * p1 ^ 6

def reduced : ℕ → P
  | 2 => reduced2
  | 3 => reduced3
  | 4 => reduced4
  | 5 => reduced5
  | 6 => reduced6
  | 7 => reduced7
  | 8 => reduced8
  | 9 => reduced9
  | 10 => reduced10
  | 11 => reduced11
  | 12 => reduced12
  | 13 => reduced13
  | 14 => reduced14
  | _ => 0

/-- The top-degree density, with the omitted power of `u` restored. -/
def density (n : ℕ) : P := u ^ (n - (n-1)/2) * reduced n

/-- The six adjacent-even identities used by the odd-dimensional proof. -/
theorem adjacent (n : ℕ) (hn : 3 ≤ n ∧ n ≤ 13) (hodd : n % 2 = 1) :
    2 * reduced n = reduced (n+1) + u * reduced (n-1) := by
  rcases hn with ⟨hlo, hhi⟩
  interval_cases n
  all_goals try { norm_num at hodd }
  all_goals apply MvPolynomial.funext
  all_goals intro v
  all_goals norm_num [Fin.cons, Fin.cases, Fin.induction, Fin.induction.go, Matrix.vecCons, reduced, reduced2, reduced3, reduced4, reduced5, reduced6, reduced7, reduced8, reduced9, reduced10, reduced11, reduced12, reduced13, reduced14]
  all_goals try dsimp only [Matrix.vecCons, Matrix.vecHead, Matrix.vecTail, Fin.cons, Fin.cases, Fin.induction, Fin.induction.go]
  all_goals norm_num [Fin.cons, Fin.cases, Fin.induction, Fin.induction.go, Matrix.vecCons, map_ofNat]
  all_goals ring

theorem density13_eq_existing : density 13 = DimensionThirteenFourteenDensity.density13 := by
  rw [DimensionThirteenFourteenDensity.density13_printed]
  apply MvPolynomial.funext
  intro v
  norm_num [Fin.cons, Fin.cases, Fin.induction, Fin.induction.go, Matrix.vecCons, density, reduced, reduced13, Nat.reduceSub, Nat.reduceDiv,
    DimensionThirteenFourteenDensity.printed13, DimensionThirteenFourteenDensity.q13]
  all_goals try dsimp only [Matrix.vecCons, Matrix.vecHead, Matrix.vecTail, Fin.cons, Fin.cases, Fin.induction, Fin.induction.go]
  all_goals norm_num [Fin.cons, Fin.cases, Fin.induction, Fin.induction.go, Matrix.vecCons, map_ofNat]
  all_goals ring

theorem density14_eq_existing : density 14 = DimensionThirteenFourteenDensity.density14 := by
  rw [DimensionThirteenFourteenDensity.density14_printed]
  apply MvPolynomial.funext
  intro v
  norm_num [Fin.cons, Fin.cases, Fin.induction, Fin.induction.go, Matrix.vecCons, density, reduced, reduced14, Nat.reduceSub, Nat.reduceDiv,
    DimensionThirteenFourteenDensity.printed14, DimensionThirteenFourteenDensity.q14]
  all_goals try dsimp only [Matrix.vecCons, Matrix.vecHead, Matrix.vecTail, Fin.cons, Fin.cases, Fin.induction, Fin.induction.go]
  all_goals norm_num [Fin.cons, Fin.cases, Fin.induction, Fin.induction.go, Matrix.vecCons, map_ofNat]
  all_goals ring

end
end QuaternionicSymmetry.KillingFieldsPaperCertificate
