import QuaternionicSymmetry.HolomorphicBundleLocalVector
import QuaternionicSymmetry.ManifoldTwistorLeBrunHolomorphicContact
import QuaternionicSymmetry.ManifoldTwistorContactComplexExact
import QuaternionicSymmetry.ManifoldTwistorContactQuotientComplex

/-! Local holomorphic sections of an actual twistor contact line obtained by
applying its actual holomorphic contact form to local tangent sections. -/
namespace QuaternionicSymmetry.ManifoldTwistorLocalContactSection
open ManifoldTwistorLeBrunComplexAtlas
open ManifoldTwistorSphereCore
open QuaternionicSymmetry.HolomorphicBundleLocalVector
open scoped Manifold ContDiff
noncomputable section

variable {E M : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [Nontrivial E] [FiniteDimensional ℝ E]
  [TopologicalSpace M] [ChartedSpace E M] [IsManifold 𝓘(ℝ,E) ∞ M]
variable (Q : ManifoldQuaternionicMetric.SmoothQuaternionicHermitianTangent
    (I := 𝓘(ℝ,E)) (M := M) (n := ∞))
  (D : ManifoldQuaternionicConnection.CompatibleTangentConnection Q)

local instance : Fact (Module.finrank ℝ ManifoldTwistorCoefficientSphere.EuclideanThree = 2 + 1) :=
  ⟨by simp⟩

/-- A prescribed tangent vector determines a local holomorphic contact-line
section by the contact form itself. -/
theorem exists_local_contact_section {n : ℕ}
    (A : CompatibleComplexAtlas Q D n)
    (C : HolomorphicContactData Q D n A)
    (z : SphereBundleTotal Q)
    (v : ComplexTwistorModel n) :
    letI := A.charts
    letI := A.complexManifold
    letI := C.line.holomorphic
    ∃ U : Set (SphereBundleTotal Q), IsOpen U ∧ z ∈ U ∧
      ∃ s : ∀ y : SphereBundleTotal Q,
        TangentSpace 𝓘(ℂ,ComplexTwistorModel n) y,
        s z = v ∧
        ContMDiffOn 𝓘(ℂ,ComplexTwistorModel n)
          ((𝓘(ℂ,ComplexTwistorModel n)).prod 𝓘(ℂ,ℂ)) ∞
          (fun y => C.line.contactFormTotal Q D
            (⟨y,s y⟩ : TangentBundle 𝓘(ℂ,ComplexTwistorModel n)
              (SphereBundleTotal Q))) U := by
  letI := A.charts
  letI := A.complexManifold
  letI := C.line.holomorphic
  let e := trivializationAt (ComplexTwistorModel n)
    (TangentSpace 𝓘(ℂ,ComplexTwistorModel n) : SphereBundleTotal Q → Type _) z
  letI : MemTrivializationAtlas e := ⟨⟨_, rfl⟩⟩
  have hz : z ∈ e.baseSet := mem_baseSet_trivializationAt
    (ComplexTwistorModel n)
    (TangentSpace 𝓘(ℂ,ComplexTwistorModel n) : SphereBundleTotal Q → Type _) z
  obtain ⟨s,hs,hsv⟩ := exists_local_section_through
    𝓘(ℂ,ComplexTwistorModel n) e z hz v
  refine ⟨e.baseSet, e.open_baseSet, hz, s, hsv, ?_⟩
  exact C.contactHolomorphic.comp_contMDiffOn hs

/-- A local holomorphic contact-line section generated by the actual form
and nonzero at the chosen point. Fiberwise surjectivity was proved from the
horizontal quotient and the compatible atlas, not added as a premise. -/
theorem exists_local_nonzero_contact_section {n : ℕ}
    (A : CompatibleComplexAtlas Q D n)
    (C : HolomorphicContactData Q D n A)
    (z : SphereBundleTotal Q) :
    letI := A.charts
    letI := A.complexManifold
    letI := C.line.holomorphic
    ∃ U : Set (SphereBundleTotal Q), IsOpen U ∧ z ∈ U ∧
      ∃ s : ∀ y : SphereBundleTotal Q,
        TangentSpace 𝓘(ℂ,ComplexTwistorModel n) y,
        ContMDiffOn 𝓘(ℂ,ComplexTwistorModel n)
          ((𝓘(ℂ,ComplexTwistorModel n)).prod 𝓘(ℂ,ℂ)) ∞
          (fun y => C.line.contactFormTotal Q D
            (⟨y,s y⟩ : TangentBundle 𝓘(ℂ,ComplexTwistorModel n)
              (SphereBundleTotal Q))) U ∧
        C.line.contactFormTotal Q D
          (⟨z,s z⟩ : TangentBundle 𝓘(ℂ,ComplexTwistorModel n)
            (SphereBundleTotal Q)) ≠ ⟨z,0⟩ := by
  letI := A.charts
  letI := A.complexManifold
  letI := C.line.holomorphic
  letI := ManifoldTwistorGlobalAlmostComplex.contactQuotientComplexModule Q D z
  have hdim : Module.finrank ℂ (C.line.core.Fiber z) = 1 :=
    (C.line.quotientEquiv z).finrank_eq.trans
      (ManifoldTwistorGlobalAlmostComplex.contactQuotient_complex_finrank Q D z)
  letI : Nontrivial (C.line.core.Fiber z) :=
    Module.nontrivial_of_finrank_pos (by rw [hdim]; omega)
  obtain ⟨w,hw⟩ := exists_ne (0 : C.line.core.Fiber z)
  obtain ⟨v,hv⟩ := C.line.contactFormComplex_surjective Q D z w
  obtain ⟨U,hU,hz,s,hsz,hs⟩ :=
    exists_local_contact_section Q D A C z v
  refine ⟨U,hU,hz,s,hs,?_⟩
  intro hzero
  have h : C.line.contactFormComplex Q D z v = 0 := by
    simpa only [HolomorphicContactLine.contactFormTotal,
      HolomorphicContactLine.contactFormComplex, hsz] using
      congrArg (fun t : Bundle.TotalSpace ℂ C.line.core.Fiber => t.2) hzero
  exact hw (hv.symm.trans h)

end
end QuaternionicSymmetry.ManifoldTwistorLocalContactSection
