import QuaternionicSymmetry.ManifoldTwistorHolomorphicMapCriterion

#check @ContMDiff
#check @QuaternionicSymmetry.ManifoldTwistorHolomorphicMapCriterion.contMDiff_complex_of_twistor_tensor
#check @ContMDiff.comp
