import QuaternionicSymmetry.ManifoldCharacteristicExpression
import Mathlib.Algebra.DirectSum.Ring

/-!
The constant-coefficient graded algebra generated by genuine de Rham classes
in degrees divisible by four. Grade `n` denotes cohomological degree `4*n`.
Its degree-zero scalar map to `H⁰` can fail to be injective when the manifold
is empty.
-/

namespace QuaternionicSymmetry.ManifoldEvenCharacteristicAlgebra

open QuaternionicSymmetry.ManifoldDifferentialForms
  QuaternionicSymmetry.ManifoldDeRhamWedge
  QuaternionicSymmetry.ManifoldDeRhamRing
open scoped Manifold ContDiff Topology

set_option synthInstance.maxHeartbeats 500000
set_option maxHeartbeats 800000

variable {E M : Type} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [TopologicalSpace M] [ChartedSpace E M]
  [IsManifold 𝓘(ℝ, E) ∞ M]

/-- Homogeneous degree `4*n` de Rham classes, with only constants in degree
zero. This is the natural target for rational characteristic polynomials. -/
def Grade (E : Type) (M : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [TopologicalSpace M] [ChartedSpace E M] [IsManifold 𝓘(ℝ, E) ∞ M] : ℕ → Type _
  | 0 => ℝ
  | n + 1 => positiveDegreeCohomology (E := E) (M₀ := M) (4 * n + 3)

noncomputable instance gradeAddCommGroup (n : ℕ) : AddCommGroup (Grade (E := E) (M := M) n) := by
  cases n with
  | zero => change AddCommGroup ℝ; infer_instance
  | succ k =>
      change AddCommGroup (positiveDegreeCohomology (E := E) (M₀ := M) (4 * k + 3))
      infer_instance

noncomputable instance gradeModule (n : ℕ) : Module ℝ (Grade (E := E) (M := M) n) := by
  cases n with
  | zero => change Module ℝ ℝ; infer_instance
  | succ k =>
      exact positiveDegreeCohomologyModule (E := E) (M := M) (4 * k + 3)

noncomputable def castGrade {p q : ℕ} (h : p = q)
    (x : Grade (E := E) (M := M) p) : Grade (E := E) (M := M) q := by
  cases h
  exact x

theorem castGrade_add {p q : ℕ} (h : p = q)
    (x y : Grade (E := E) (M := M) p) :
    castGrade h (x + y) = castGrade h x + castGrade h y := by
  cases h
  rfl

theorem castGrade_smul {p q : ℕ} (h : p = q) (c : ℝ)
    (x : Grade (E := E) (M := M) p) :
    castGrade h (c • x) = c • castGrade h x := by
  cases h
  rfl

theorem castGrade_symm_cancel {p q : ℕ} (h : p = q)
    (x : Grade (E := E) (M := M) q) :
    castGrade h (castGrade h.symm x) = x := by
  cases h
  rfl

theorem castGrade_comp {p q r : ℕ} (h : p = q) (g : q = r)
    (x : Grade (E := E) (M := M) p) :
    castGrade g (castGrade h x) = castGrade (h.trans g) x := by
  cases h
  cases g
  rfl

@[simp] theorem castGrade_same {p : ℕ} (h : p = p)
    (x : Grade (E := E) (M := M) p) : castGrade h x = x := by
  cases h
  rfl

private theorem castGrade_positive {p q : ℕ} (h : p + 1 = q + 1)
    (x : Grade (E := E) (M := M) (p + 1)) :
    castGrade h x =
      castClass (show 4 * p + 3 = 4 * q + 3 by omega) x := by
  cases h
  rfl

/-- The actual wedge product for positive grades and ordinary scalar action
for degree-zero coefficients. -/
noncomputable def gradeMul : (p q : ℕ) →
    Grade (E := E) (M := M) p → Grade (E := E) (M := M) q →
      Grade (E := E) (M := M) (p + q)
  | 0, 0, a, b => by
      change ℝ at a b
      change ℝ
      exact a * b
  | 0, l + 1, a, b => by
      change ℝ at a
      change positiveDegreeCohomology (E := E) (M₀ := M) (4 * l + 3) at b
      exact castGrade (Nat.zero_add (l + 1)).symm (a • b)
  | k + 1, 0, a, b => by
      change ℝ at b
      change positiveDegreeCohomology (E := E) (M₀ := M) (4 * k + 3) at a
      exact b • a
  | k + 1, l + 1, a, b =>
      castClass (show (4 * k + 3) + (4 * l + 3) + 1 =
        4 * ((k + 1) + l) + 3 by omega)
        (cohomologyWedge (4 * k + 3) (4 * l + 3) a b)

theorem gradeMul_cast_left {p p' q : ℕ} (h : p = p')
    (a : Grade (E := E) (M := M) p)
    (b : Grade (E := E) (M := M) q) :
    gradeMul p' q (castGrade h a) b =
      castGrade (congrArg (· + q) h) (gradeMul p q a b) := by
  cases h
  rfl

theorem gradeMul_cast_right {p q q' : ℕ} (h : q = q')
    (a : Grade (E := E) (M := M) p)
    (b : Grade (E := E) (M := M) q) :
    gradeMul p q' a (castGrade h b) =
      castGrade (congrArg (p + ·) h) (gradeMul p q a b) := by
  cases h
  rfl

private theorem castClass_add {a b : ℕ} (h : a = b)
    (x y : positiveDegreeCohomology (E := E) (M₀ := M) a) :
    castClass h (x + y) = castClass h x + castClass h y := by
  cases h
  rfl

private theorem castClass_smul {a b : ℕ} (h : a = b) (c : ℝ)
    (x : positiveDegreeCohomology (E := E) (M₀ := M) a) :
    castClass h (c • x) = c • castClass h x := by
  cases h
  rfl

private theorem castClass_comp {a b c : ℕ} (h : a = b) (g : b = c)
    (x : positiveDegreeCohomology (E := E) (M₀ := M) a) :
    castClass g (castClass h x) = castClass (h.trans g) x := by
  cases h
  cases g
  rfl

private theorem cohomologyWedge_cast_left {a b l : ℕ} (h : a = b)
    (x : positiveDegreeCohomology (E := E) (M₀ := M) a)
    (y : positiveDegreeCohomology (E := E) (M₀ := M) l) :
    cohomologyWedge b l (castClass h x) y =
      castClass (show a + l + 1 = b + l + 1 by omega)
        (cohomologyWedge a l x y) := by
  cases h
  rfl

private theorem cohomologyWedge_cast_right {a b k : ℕ} (h : a = b)
    (x : positiveDegreeCohomology (E := E) (M₀ := M) k)
    (y : positiveDegreeCohomology (E := E) (M₀ := M) a) :
    cohomologyWedge k b x (castClass h y) =
      castClass (show k + a + 1 = k + b + 1 by omega)
        (cohomologyWedge k a x y) := by
  cases h
  rfl

theorem gradeMul_add_left (p q : ℕ)
    (a b : Grade (E := E) (M := M) p)
    (c : Grade (E := E) (M := M) q) :
    gradeMul p q (a + b) c = gradeMul p q a c + gradeMul p q b c := by
  cases p with
  | zero =>
      cases q with
      | zero => simp [gradeMul, add_mul]
      | succ l =>
          change ℝ at a b
          change positiveDegreeCohomology (E := E) (M₀ := M) (4 * l + 3) at c
          change castGrade (E := E) (M := M) (Nat.zero_add (l + 1)).symm
              ((a + b) • c) =
            castGrade (E := E) (M := M) (Nat.zero_add (l + 1)).symm (a • c) +
              castGrade (E := E) (M := M) (Nat.zero_add (l + 1)).symm (b • c)
          rw [add_smul, castGrade_add]
  | succ k =>
      cases q with
      | zero => simp [gradeMul, smul_add]
      | succ l =>
          change castClass _ (cohomologyWedge _ _ (a + b) c) =
            castClass _ (cohomologyWedge _ _ a c) +
              castClass _ (cohomologyWedge _ _ b c)
          rw [cohomologyWedge_add_left, castClass_add]

theorem gradeMul_add_right (p q : ℕ)
    (a : Grade (E := E) (M := M) p)
    (b c : Grade (E := E) (M := M) q) :
    gradeMul p q a (b + c) = gradeMul p q a b + gradeMul p q a c := by
  cases p with
  | zero =>
      cases q with
      | zero => simp [gradeMul, mul_add]
      | succ l =>
          change ℝ at a
          change positiveDegreeCohomology (E := E) (M₀ := M) (4 * l + 3) at b c
          change castGrade (E := E) (M := M) (Nat.zero_add (l + 1)).symm
              (a • (b + c)) =
            castGrade (E := E) (M := M) (Nat.zero_add (l + 1)).symm (a • b) +
              castGrade (E := E) (M := M) (Nat.zero_add (l + 1)).symm (a • c)
          rw [smul_add, castGrade_add]
  | succ k =>
      cases q with
      | zero => simp [gradeMul, add_smul]
      | succ l =>
          change castClass _ (cohomologyWedge _ _ a (b + c)) =
            castClass _ (cohomologyWedge _ _ a b) +
              castClass _ (cohomologyWedge _ _ a c)
          rw [cohomologyWedge_add_right, castClass_add]

theorem gradeMul_one_left (q : ℕ)
    (b : Grade (E := E) (M := M) q) :
    castGrade (Nat.zero_add q) (gradeMul 0 q (1 : ℝ) b) = b := by
  cases q with
  | zero =>
      change ℝ at b
      change (1 : ℝ) * b = b
      exact one_mul b
  | succ l =>
      change castGrade (Nat.zero_add (l + 1))
        (castGrade (Nat.zero_add (l + 1)).symm ((1 : ℝ) • b)) = b
      rw [one_smul, castGrade_symm_cancel]

theorem gradeMul_one_right (p : ℕ)
    (a : Grade (E := E) (M := M) p) :
    gradeMul p 0 a (1 : ℝ) = a := by
  cases p with
  | zero =>
      change ℝ at a
      change a * (1 : ℝ) = a
      exact mul_one a
  | succ k =>
      change (1 : ℝ) • a = a
      exact one_smul ℝ a

theorem gradeMul_assoc_positive (k l m : ℕ)
    (a : Grade (E := E) (M := M) (k + 1))
    (b : Grade (E := E) (M := M) (l + 1))
    (c : Grade (E := E) (M := M) (m + 1)) :
    castGrade (Nat.add_assoc (k + 1) (l + 1) (m + 1))
      (gradeMul ((k + 1) + (l + 1)) (m + 1)
        (gradeMul (k + 1) (l + 1) a b) c) =
      gradeMul (k + 1) ((l + 1) + (m + 1)) a
        (gradeMul (l + 1) (m + 1) b c) := by
  rw [castGrade_positive]
  dsimp only [gradeMul]
  rw [cohomologyWedge_cast_left, cohomologyWedge_cast_right]
  rw [castClass_comp, castClass_comp]
  rw [← cohomologyWedge_assoc (4 * k + 3) (4 * l + 3) (4 * m + 3) a b c]
  repeat' rw [castClass_comp]

theorem gradeMul_comm_positive (k l : ℕ)
    (a : Grade (E := E) (M := M) (k + 1))
    (b : Grade (E := E) (M := M) (l + 1)) :
    castGrade (Nat.add_comm (l + 1) (k + 1))
      (gradeMul (l + 1) (k + 1) b a) =
        gradeMul (k + 1) (l + 1) a b := by
  rw [castGrade_positive]
  dsimp only [gradeMul]
  rw [castClass_comp]
  have hswap := cohomologyWedge_swap (4 * k + 3) (4 * l + 3) a b
  have heven : Even (((4 * k + 3) + 1) * ((4 * l + 3) + 1)) := by
    refine ⟨8 * (k + 1) * (l + 1), ?_⟩
    ring
  rw [heven.neg_one_pow, one_smul] at hswap
  rw [← hswap]
  rw [castClass_comp]

theorem gradeMul_smul_left_positive (k l : ℕ) (c : ℝ)
    (a : Grade (E := E) (M := M) (k + 1))
    (b : Grade (E := E) (M := M) (l + 1)) :
    gradeMul (k + 1) (l + 1) (c • a) b =
      c • gradeMul (k + 1) (l + 1) a b := by
  change castClass _ (cohomologyWedge _ _ (c • a) b) =
    c • castClass _ (cohomologyWedge _ _ a b)
  rw [← cohomologyScalar_eq_smul (4 * k + 3) c a]
  rw [cohomologyWedge_smul_left,
    cohomologyScalar_eq_smul (4 * k + 3 + (4 * l + 3) + 1), castClass_smul]

theorem gradeMul_smul_right_positive (k l : ℕ) (c : ℝ)
    (a : Grade (E := E) (M := M) (k + 1))
    (b : Grade (E := E) (M := M) (l + 1)) :
    gradeMul (k + 1) (l + 1) a (c • b) =
      c • gradeMul (k + 1) (l + 1) a b := by
  change castClass _ (cohomologyWedge _ _ a (c • b)) =
    c • castClass _ (cohomologyWedge _ _ a b)
  rw [← cohomologyScalar_eq_smul (4 * l + 3) c b]
  rw [cohomologyWedge_smul_right,
    cohomologyScalar_eq_smul (4 * k + 3 + (4 * l + 3) + 1), castClass_smul]

theorem gradeMul_comm (p q : ℕ)
    (a : Grade (E := E) (M := M) p)
    (b : Grade (E := E) (M := M) q) :
    castGrade (Nat.add_comm q p) (gradeMul q p b a) = gradeMul p q a b := by
  cases p with
  | zero =>
      cases q with
      | zero =>
          change ℝ at a b
          change b * a = a * b
          exact mul_comm b a
      | succ l =>
          change ℝ at a
          change positiveDegreeCohomology (E := E) (M₀ := M) (4 * l + 3) at b
          change castGrade (Nat.add_comm (l + 1) 0) (a • b) =
            castGrade (Nat.zero_add (l + 1)).symm (a • b)
          rfl
  | succ k =>
      cases q with
      | zero =>
          change ℝ at b
          change positiveDegreeCohomology (E := E) (M₀ := M) (4 * k + 3) at a
          change castGrade (Nat.add_comm 0 (k + 1))
              (castGrade (Nat.zero_add (k + 1)).symm (b • a)) = b • a
          exact castGrade_symm_cancel (Nat.zero_add (k + 1)) (b • a)
      | succ l => exact gradeMul_comm_positive k l a b

theorem gradeMul_assoc (p q r : ℕ)
    (a : Grade (E := E) (M := M) p)
    (b : Grade (E := E) (M := M) q)
    (c : Grade (E := E) (M := M) r) :
    castGrade (Nat.add_assoc p q r)
      (gradeMul (p + q) r (gradeMul p q a b) c) =
      gradeMul p (q + r) a (gradeMul q r b c) := by
  cases p with
  | zero =>
      cases q with
      | zero =>
          cases r with
          | zero =>
              change ℝ at a b c
              change (a * b) * c = a * (b * c)
              exact mul_assoc a b c
          | succ m =>
              change ℝ at a b
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * m + 3) at c
              simp only [gradeMul, id_eq]
              rw [← castGrade_smul]
              repeat' rw [castGrade_comp]
              rw [mul_smul]
      | succ l =>
          cases r with
          | zero =>
              change ℝ at a c
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * l + 3) at b
              simp only [gradeMul, id_eq]
              rw [← castGrade_smul, castGrade_comp]
              rw [smul_smul, smul_smul, mul_comm c a]
          | succ m =>
              change ℝ at a
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * l + 3) at b
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * m + 3) at c
              change castGrade (Nat.add_assoc 0 (l + 1) (m + 1))
                  (gradeMul (0 + (l + 1)) (m + 1)
                    (castGrade (Nat.zero_add (l + 1)).symm (a • b)) c) =
                castGrade (Nat.zero_add ((l + 1) + (m + 1))).symm
                  (a • gradeMul (l + 1) (m + 1) b c)
              rw [gradeMul_cast_left]
              rw [gradeMul_smul_left_positive]
              repeat' rw [castGrade_comp]
  | succ k =>
      cases q with
      | zero =>
          cases r with
          | zero =>
              change ℝ at b c
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * k + 3) at a
              simp only [gradeMul, id_eq]
              rw [smul_smul, mul_comm c b]
              rw [castGrade_same]
          | succ m =>
              change ℝ at b
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * k + 3) at a
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * m + 3) at c
              simp only [gradeMul, id_eq]
              repeat' rw [castGrade_positive]
              rw [cohomologyWedge_cast_right]
              rw [← cohomologyScalar_eq_smul (4 * k + 3) b a,
                ← cohomologyScalar_eq_smul (4 * m + 3) b c]
              rw [cohomologyWedge_smul_left, cohomologyWedge_smul_right]
              rw [cohomologyScalar_eq_smul (4 * k + 3 + (4 * m + 3) + 1)]
              repeat' rw [castClass_smul]
              repeat' rw [castClass_comp]
      | succ l =>
          cases r with
          | zero =>
              change ℝ at c
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * k + 3) at a
              change positiveDegreeCohomology (E := E) (M₀ := M) (4 * l + 3) at b
              simp only [gradeMul, id_eq]
              rw [castGrade_positive]
              rw [← cohomologyScalar_eq_smul (4 * l + 3) c b]
              rw [cohomologyWedge_smul_right,
                cohomologyScalar_eq_smul (4 * k + 3 + (4 * l + 3) + 1)]
              repeat' rw [castClass_smul]
              repeat' rw [castClass_comp]
          | succ m => exact gradeMul_assoc_positive k l m a b c

theorem gradeMul_zero_left (p q : ℕ)
    (b : Grade (E := E) (M := M) q) :
    gradeMul p q (0 : Grade (E := E) (M := M) p) b = 0 := by
  let x := gradeMul p q (0 : Grade (E := E) (M := M) p) b
  have h : x = x + x := by
    simpa [x] using gradeMul_add_left p q
      (0 : Grade (E := E) (M := M) p) 0 b
  have h' : x + x = x + 0 := by
    calc x + x = x := h.symm
      _ = x + 0 := (add_zero x).symm
  exact add_left_cancel h'

theorem gradeMul_zero_right (p q : ℕ)
    (a : Grade (E := E) (M := M) p) :
    gradeMul p q a (0 : Grade (E := E) (M := M) q) = 0 := by
  let x := gradeMul p q a (0 : Grade (E := E) (M := M) q)
  have h : x = x + x := by
    simpa [x] using gradeMul_add_right p q a
      (0 : Grade (E := E) (M := M) q) 0
  have h' : x + x = x + 0 := by
    calc x + x = x := h.symm
      _ = x + 0 := (add_zero x).symm
  exact add_left_cancel h'

private theorem heq_of_castGrade_eq {p q : ℕ} (h : p = q)
    (x : Grade (E := E) (M := M) p)
    (y : Grade (E := E) (M := M) q)
    (hxy : castGrade h x = y) : HEq x y := by
  cases h
  exact heq_of_eq hxy

noncomputable instance gradedMul : GradedMonoid.GMul (Grade (E := E) (M := M)) where
  mul := fun {i j} a b => gradeMul i j a b

noncomputable instance gradedOne : GradedMonoid.GOne (Grade (E := E) (M := M)) where
  one := (1 : ℝ)

/-- The direct sum of constant coefficients and degree-`4n` de Rham groups
forms a commutative ring under the actual wedge product. -/
noncomputable instance gradedCommRing :
    DirectSum.GCommRing (Grade (E := E) (M := M)) where
  mul := fun {i j} a b => gradeMul i j a b
  one := (1 : ℝ)
  mul_zero := by
    intro i j a
    exact gradeMul_zero_right i j a
  zero_mul := by
    intro i j b
    exact gradeMul_zero_left i j b
  mul_add := by
    intro i j a b c
    exact gradeMul_add_right i j a b c
  add_mul := by
    intro i j a b c
    exact gradeMul_add_left i j a b c
  one_mul := by
    rintro ⟨i, a⟩
    exact Sigma.ext (Nat.zero_add i)
      (heq_of_castGrade_eq (Nat.zero_add i) _ _ (gradeMul_one_left i a))
  mul_one := by
    rintro ⟨i, a⟩
    exact Sigma.ext (Nat.add_zero i) (heq_of_eq (gradeMul_one_right i a))
  mul_assoc := by
    rintro ⟨i, a⟩ ⟨j, b⟩ ⟨k, c⟩
    exact Sigma.ext (Nat.add_assoc i j k)
      (heq_of_castGrade_eq (Nat.add_assoc i j k) _ _ (gradeMul_assoc i j k a b c))
  mul_comm := by
    rintro ⟨i, a⟩ ⟨j, b⟩
    exact Sigma.ext (Nat.add_comm i j)
      (heq_of_castGrade_eq (Nat.add_comm i j) _ _ (gradeMul_comm j i b a))
  natCast := fun n => (n : ℝ)
  natCast_zero := by norm_num
  natCast_succ := by intro n; norm_num
  intCast := fun z => (z : ℝ)
  intCast_ofNat := by intro n; norm_num
  intCast_negSucc_ofNat := by intro n; norm_num

/-- Finite sums of homogeneous even de Rham classes. -/
abbrev Total : Type := DirectSum ℕ (Grade (E := E) (M := M))

noncomputable instance totalCommRing : CommRing (Total (E := E) (M := M)) :=
  DirectSum.commRing (Grade (E := E) (M := M))

/-- Rational constants occupy grade zero. -/
noncomputable def rationalConstants : ℚ →+* Total (E := E) (M := M) :=
  (DirectSum.ofZeroRingHom (Grade (E := E) (M := M))).comp (algebraMap ℚ ℝ)

end QuaternionicSymmetry.ManifoldEvenCharacteristicAlgebra
