import QuaternionicSymmetry.ManifoldQuaternionicChernWeil
import QuaternionicSymmetry.ManifoldChernWeilGaugeHomotopy
import QuaternionicSymmetry.LocalOrderedPrimitiveSmoothness

/-!
Two smooth compatible tangent connections on the same actual quaternionic
tangent reduction determine equal Chern--Weil de Rham classes. Their
difference transforms homogeneously, and analytic regularity of the endpoint
trace and ordered primitive follows from the smooth local forms.
-/

namespace QuaternionicSymmetry.ManifoldQuaternionicChernWeilIndependence

open Filter QuaternionicSymmetry.ManifoldDifferentialForms
  QuaternionicSymmetry.ManifoldQuaternionicConnection
  QuaternionicSymmetry.ManifoldQuaternionicChernWeil
  QuaternionicSymmetry.ManifoldChernWeilGaugeHomotopy
  QuaternionicSymmetry.LocalChernWeilSmoothness
  QuaternionicSymmetry.LocalOrderedPrimitiveSmoothness
  QuaternionicSymmetry.LocalConnectionCoordinatePullback
  QuaternionicSymmetry.LocalConnection
open scoped Manifold Topology ContDiff

variable {E M : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [FiniteDimensional ℝ E]
  [TopologicalSpace M] [ChartedSpace E M]
  [IsManifold 𝓘(ℝ, E) ∞ M]

noncomputable section

variable (Q : QuaternionicSymmetry.ManifoldQuaternionicMetric.SmoothQuaternionicHermitianTangent
  (I := 𝓘(ℝ, E)) (M := M) (n := ∞))
variable (D₀ D₁ : CompatibleTangentConnection Q)

omit [FiniteDimensional ℝ E] in
private theorem pullback_sub (Γ₁ Γ₀ : ConnectionForm (E := E))
    (φ : E → E) :
    pullback (Γ₁ - Γ₀) φ = pullback Γ₁ φ - pullback Γ₀ φ := by
  funext x
  ext v
  rfl

omit [FiniteDimensional ℝ E] in
private theorem transform_sub (Γ₁ Γ₀ : ConnectionForm (E := E))
    (g h : E → Endomorphism (E := E)) :
    QuaternionicSymmetry.LocalConnectionGauge.transform Γ₁ g h -
      QuaternionicSymmetry.LocalConnectionGauge.transform Γ₀ g h =
    QuaternionicSymmetry.LocalConnectionGauge.adjointForm (Γ₁ - Γ₀) g h := by
  funext x
  apply ContinuousLinearMap.ext
  intro v
  simp only [Pi.sub_apply, ContinuousLinearMap.sub_apply,
    QuaternionicSymmetry.LocalConnectionGauge.transform_apply,
    QuaternionicSymmetry.LocalConnectionGauge.adjointForm_apply]
  noncomm_ring

omit [FiniteDimensional ℝ E] in
/-- The difference of two actual compatible tangent connections has the
homogeneous frame and chart transition law. -/
theorem directionGaugeLaw (p q : M) (y : E)
    (hy : y ∈ chartOverlap (I := 𝓘(ℝ, E)) p q) :
    (fun r => D₁.form r - D₀.form r) p =ᶠ[𝓝 y]
      QuaternionicSymmetry.LocalConnectionGauge.adjointForm
        (pullback (D₁.form q - D₀.form q)
          (chartTransition (I := 𝓘(ℝ, E)) p q))
        (adaptedGauge Q p q) (adaptedGaugeInv Q p q) := by
  filter_upwards [(chartOverlap_isOpen (I := 𝓘(ℝ, E)) p q).mem_nhds hy]
    with z hz
  simp only [Pi.sub_apply]
  rw [D₁.overlap p q z hz, D₀.overlap p q z hz]
  rw [pullback_sub]
  exact congrFun (transform_sub
    (pullback (D₁.form q) (chartTransition (I := 𝓘(ℝ, E)) p q))
    (pullback (D₀.form q) (chartTransition (I := 𝓘(ℝ, E)) p q))
    (adaptedGauge Q p q) (adaptedGaugeInv Q p q)) z

/-- The complete Chern--Weil homotopy generated by two compatible tangent
connections; all scalar transition and regularity laws are derived. -/
def gaugeHomotopy (k : ℕ) :
    GaugeCoordinateHomotopy (E := E) (M := M) (V := E) k where
  start := gaugeAtlas (Q := Q) (D := D₀) k
  direction p := D₁.form p - D₀.form p
  directionC2 p y hy := by
    exact (((D₁.smooth_form p).sub (D₀.smooth_form p)).contDiffAt
      ((isOpen_extChartAt_target (I := 𝓘(ℝ, E)) p).mem_nhds hy)).of_le (by exact ENat.LEInfty.out)
  directionGaugeLaw p q y hp hq :=
    directionGaugeLaw Q D₀ D₁ p q y ⟨hp, hq⟩
  endpointTraceRegular p := by
    exact tracePowerForm_contDiffOn
      QuaternionicSymmetry.LocalEndomorphismTrace.traceCLM
      (D₀.form p + (D₁.form p - D₀.form p))
      (isOpen_extChartAt_target (I := 𝓘(ℝ, E)) p)
      ((D₀.smooth_form p).add ((D₁.smooth_form p).sub (D₀.smooth_form p))) k
  primitiveRegular p := by
    exact traceOrderedTransgressionForm_contDiffOn
      QuaternionicSymmetry.LocalEndomorphismTrace.traceCLM
      (D₀.form p) (D₁.form p - D₀.form p)
      (isOpen_extChartAt_target (I := 𝓘(ℝ, E)) p)
      (D₀.smooth_form p)
      ((D₁.smooth_form p).sub (D₀.smooth_form p)) k

/-- At the endpoint, the affine path is exactly the second connection. -/
theorem finish_connection (k : ℕ) (p : M) :
    ((gaugeHomotopy Q D₀ D₁ k).finish).connection p = D₁.form p := by
  funext x
  change D₀.form p x + (D₁.form p x - D₀.form p x) = D₁.form p x
  abel

theorem finish_globalTracePower (k : ℕ) :
    ((gaugeHomotopy Q D₀ D₁ k).toTracePowerHomotopy.finish).globalForm =
      globalTracePower (Q := Q) (D := D₁) k := by
  funext x
  change
    (QuaternionicSymmetry.LocalChernWeilTracePowers.traceCurvaturePowerForm
      (((gaugeHomotopy Q D₀ D₁ k).finish).connection x) k
        (extChartAt 𝓘(ℝ, E) x x)).compContinuousLinearMap _ =
      (QuaternionicSymmetry.LocalChernWeilTracePowers.traceCurvaturePowerForm
        (D₁.form x) k (extChartAt 𝓘(ℝ, E) x x)).compContinuousLinearMap _
  rw [finish_connection]

/-- The two compatible tangent connections have the same actual
Chern--Weil de Rham class in every positive degree. -/
theorem tracePowerClass_eq (k : ℕ) :
    QuotientAddGroup.mk
      ((QuaternionicSymmetry.LocalChernWeilOrderedTransgression.primitiveDegree_add_one k).symm ▸
        ((gaugeAtlas (Q := Q) (D := D₁) k).toTracePowerAtlas.closedGlobalForm)) =
    (QuotientAddGroup.mk
      ((QuaternionicSymmetry.LocalChernWeilOrderedTransgression.primitiveDegree_add_one k).symm ▸
        ((gaugeAtlas (Q := Q) (D := D₀) k).toTracePowerAtlas.closedGlobalForm)) :
          positiveDegreeCohomology (E := E) (M₀ := M)
            (QuaternionicSymmetry.LocalChernWeilOrderedTransgression.primitiveDegree k)) := by
  have hfinish :
      ((gaugeHomotopy Q D₀ D₁ k).toTracePowerHomotopy.finish).closedGlobalForm =
        ((gaugeAtlas (Q := Q) (D := D₁) k).toTracePowerAtlas).closedGlobalForm := by
    apply Subtype.ext
    apply Subtype.ext
    exact finish_globalTracePower Q D₀ D₁ k
  have h := (gaugeHomotopy Q D₀ D₁ k).cohomologyClass_eq
  rw [hfinish] at h
  exact h

/-- Connection independence in the actual de Rham quotient, with the
second endpoint represented by the affine path from the first. -/
theorem cohomologyClass_eq (k : ℕ) :
    QuotientAddGroup.mk
      ((QuaternionicSymmetry.LocalChernWeilOrderedTransgression.primitiveDegree_add_one k).symm ▸
        ((gaugeHomotopy Q D₀ D₁ k).toTracePowerHomotopy.finish.closedGlobalForm)) =
    (QuotientAddGroup.mk
      ((QuaternionicSymmetry.LocalChernWeilOrderedTransgression.primitiveDegree_add_one k).symm ▸
        ((gaugeHomotopy Q D₀ D₁ k).toTracePowerHomotopy.start.closedGlobalForm)) :
          positiveDegreeCohomology (E := E) (M₀ := M)
            (QuaternionicSymmetry.LocalChernWeilOrderedTransgression.primitiveDegree k)) :=
  (gaugeHomotopy Q D₀ D₁ k).cohomologyClass_eq

end
end QuaternionicSymmetry.ManifoldQuaternionicChernWeilIndependence
