import QuaternionicSymmetry.QuaternionicStructure
import Mathlib.LinearAlgebra.Dimension.Finite

/-!
  Four-vector frames generated by a quaternionic Hermitian structure.

  The results are pointwise linear algebra: a nonzero vector generates an
  orthogonal quaternionic four-plane.
-/

namespace QuaternionicSymmetry
namespace QuaternionicStructure

variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℝ V]

/-- The quaternionic four-frame generated by `v`. -/
def frame (Q : QuaternionicStructure V) (v : V) : Fin 4 → V :=
  ![v, Q.I v, Q.J v, Q.K v]

private theorem inner_zero_of_skew (E : V ≃ₗᵢ[ℝ] V)
    (hE : ∀ v w : V, inner ℝ (E v) w = -inner ℝ v (E w)) (v : V) :
    inner ℝ v (E v) = 0 := by
  have h := hE v v
  rw [real_inner_comm] at h
  linarith

private theorem inner_v_I (Q : QuaternionicStructure V) (v : V) : inner ℝ v (Q.I v) = 0 :=
  inner_zero_of_skew Q.I Q.I_skew v

private theorem inner_v_J (Q : QuaternionicStructure V) (v : V) : inner ℝ v (Q.J v) = 0 :=
  inner_zero_of_skew Q.J Q.J_skew v

private theorem inner_v_K (Q : QuaternionicStructure V) (v : V) : inner ℝ v (Q.K v) = 0 :=
  inner_zero_of_skew Q.K Q.K_skew v

private theorem K_I_apply (Q : QuaternionicStructure V) (v : V) : Q.K (Q.I v) = Q.J v := by
  change Q.I (Q.J (Q.I v)) = Q.J v
  rw [Q.J_I_anti, map_neg, Q.I_sq]
  simp

private theorem I_K_apply (Q : QuaternionicStructure V) (v : V) : Q.I (Q.K v) = -Q.J v := by
  change Q.I (Q.I (Q.J v)) = -Q.J v
  exact Q.I_sq (Q.J v)

private theorem J_K_apply (Q : QuaternionicStructure V) (v : V) : Q.J (Q.K v) = Q.I v := by
  change Q.J (Q.I (Q.J v)) = Q.I v
  rw [Q.J_I_anti, Q.J_sq]
  simp

private theorem K_J_apply (Q : QuaternionicStructure V) (v : V) : Q.K (Q.J v) = -Q.I v := by
  change Q.I (Q.J (Q.J v)) = -Q.I v
  rw [Q.J_sq]
  exact Q.I.map_neg v

private theorem inner_I_J (Q : QuaternionicStructure V) (v : V) :
    inner ℝ (Q.I v) (Q.J v) = 0 := by
  rw [Q.I_skew]
  change -inner ℝ v (Q.K v) = 0
  exact neg_eq_zero.mpr (inner_v_K Q v)

private theorem inner_v_IJ (Q : QuaternionicStructure V) (v : V) :
    inner ℝ v (Q.I (Q.J v)) = 0 := by
  simpa using inner_v_K Q v

private theorem inner_I_K (Q : QuaternionicStructure V) (v : V) :
    inner ℝ (Q.I v) (Q.K v) = 0 := by
  rw [Q.I_skew, I_K_apply]
  simpa using inner_v_J Q v

private theorem inner_J_K (Q : QuaternionicStructure V) (v : V) :
    inner ℝ (Q.J v) (Q.K v) = 0 := by
  rw [Q.J_skew, J_K_apply]
  exact neg_eq_zero.mpr (inner_v_I Q v)

/-- The Gram matrix of the quaternionic frame is diagonal. -/
theorem frame_gram (Q : QuaternionicStructure V) (v : V) (i j : Fin 4) :
    inner ℝ (Q.frame v i) (Q.frame v j) = if i = j then inner ℝ v v else 0 := by
  fin_cases i <;> fin_cases j <;>
    simp [frame, inner_v_I, inner_v_J, inner_v_IJ, inner_I_J,
      real_inner_comm, Q.I.inner_map_map]

/-- A unit vector and its quaternionic translates form an orthonormal four-frame. -/
theorem frame_orthonormal (Q : QuaternionicStructure V) (v : V) (hv : ‖v‖ = 1) :
    Orthonormal ℝ (Q.frame v) := by
  rw [orthonormal_iff_ite]
  intro i j
  rw [Q.frame_gram]
  simp [hv]

theorem frame_linearIndependent (Q : QuaternionicStructure V) (v : V) (hv : ‖v‖ = 1) :
    LinearIndependent ℝ (Q.frame v) :=
  (Q.frame_orthonormal v hv).linearIndependent

theorem finrank_ge_four (Q : QuaternionicStructure V) [FiniteDimensional ℝ V]
    (v : V) (hv : ‖v‖ = 1) : 4 ≤ Module.finrank ℝ V := by
  simpa using (Q.frame_linearIndependent v hv).fintype_card_le_finrank

/-- The quaternionic four-plane generated by `v`. -/
def frameSpan (Q : QuaternionicStructure V) (v : V) : Submodule ℝ V :=
  Submodule.span ℝ (Set.range (Q.frame v))

private theorem frame_mem_span (Q : QuaternionicStructure V) (v : V) (i : Fin 4) :
    Q.frame v i ∈ Q.frameSpan v :=
  Submodule.subset_span ⟨i, rfl⟩

theorem I_stable_frameSpan (Q : QuaternionicStructure V) (v : V) {x : V}
    (hx : x ∈ Q.frameSpan v) : Q.I x ∈ Q.frameSpan v := by
  have hmap : Submodule.map Q.I.toLinearEquiv.toLinearMap (Q.frameSpan v) ≤ Q.frameSpan v := by
    rw [frameSpan, Submodule.map_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    fin_cases i
    · change Q.I v ∈ Q.frameSpan v
      exact frame_mem_span Q v 1
    · change Q.I (Q.I v) ∈ Q.frameSpan v
      rw [Q.I_sq]
      exact (Q.frameSpan v).neg_mem (frame_mem_span Q v 0)
    · change Q.I (Q.J v) ∈ Q.frameSpan v
      exact frame_mem_span Q v 3
    · change Q.I (Q.K v) ∈ Q.frameSpan v
      rw [I_K_apply]
      exact (Q.frameSpan v).neg_mem (frame_mem_span Q v 2)
  apply hmap
  exact ⟨x, hx, rfl⟩

theorem J_stable_frameSpan (Q : QuaternionicStructure V) (v : V) {x : V}
    (hx : x ∈ Q.frameSpan v) : Q.J x ∈ Q.frameSpan v := by
  have hmap : Submodule.map Q.J.toLinearEquiv.toLinearMap (Q.frameSpan v) ≤ Q.frameSpan v := by
    rw [frameSpan, Submodule.map_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    fin_cases i
    · change Q.J v ∈ Q.frameSpan v
      exact frame_mem_span Q v 2
    · change Q.J (Q.I v) ∈ Q.frameSpan v
      rw [Q.J_I_anti]
      exact (Q.frameSpan v).neg_mem (frame_mem_span Q v 3)
    · change Q.J (Q.J v) ∈ Q.frameSpan v
      rw [Q.J_sq]
      exact (Q.frameSpan v).neg_mem (frame_mem_span Q v 0)
    · change Q.J (Q.K v) ∈ Q.frameSpan v
      rw [J_K_apply]
      exact frame_mem_span Q v 1
  apply hmap
  exact ⟨x, hx, rfl⟩

theorem K_stable_frameSpan (Q : QuaternionicStructure V) (v : V) {x : V}
    (hx : x ∈ Q.frameSpan v) : Q.K x ∈ Q.frameSpan v := by
  have hmap : Submodule.map Q.K.toLinearEquiv.toLinearMap (Q.frameSpan v) ≤ Q.frameSpan v := by
    rw [frameSpan, Submodule.map_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    fin_cases i
    · change Q.K v ∈ Q.frameSpan v
      exact frame_mem_span Q v 3
    · change Q.K (Q.I v) ∈ Q.frameSpan v
      rw [K_I_apply]
      exact frame_mem_span Q v 2
    · change Q.K (Q.J v) ∈ Q.frameSpan v
      rw [K_J_apply]
      exact (Q.frameSpan v).neg_mem (frame_mem_span Q v 1)
    · change Q.K (Q.K v) ∈ Q.frameSpan v
      rw [Q.K_sq]
      exact (Q.frameSpan v).neg_mem (frame_mem_span Q v 0)
  apply hmap
  exact ⟨x, hx, rfl⟩

/-- A skew-adjoint map preserving a subspace also preserves its orthogonal complement. -/
theorem orthogonal_stable_of_skew (A : V →ₗ[ℝ] V)
    (hskew : ∀ x y : V, inner ℝ (A x) y = -inner ℝ x (A y))
    (S : Submodule ℝ V) (hS : ∀ y : V, y ∈ S → A y ∈ S) {x : V}
    (hx : x ∈ S.orthogonal) : A x ∈ S.orthogonal := by
  rw [Submodule.mem_orthogonal'] at hx ⊢
  intro y hy
  rw [hskew]
  exact neg_eq_zero.mpr (hx (A y) (hS y hy))

theorem I_stable_frameSpan_orthogonal (Q : QuaternionicStructure V) (v : V) {x : V}
    (hx : x ∈ (Q.frameSpan v).orthogonal) : Q.I x ∈ (Q.frameSpan v).orthogonal := by
  rw [Submodule.mem_orthogonal'] at hx ⊢
  intro y hy
  rw [Q.I_skew]
  exact neg_eq_zero.mpr (hx (Q.I y) (Q.I_stable_frameSpan v hy))

theorem J_stable_frameSpan_orthogonal (Q : QuaternionicStructure V) (v : V) {x : V}
    (hx : x ∈ (Q.frameSpan v).orthogonal) : Q.J x ∈ (Q.frameSpan v).orthogonal := by
  rw [Submodule.mem_orthogonal'] at hx ⊢
  intro y hy
  rw [Q.J_skew]
  exact neg_eq_zero.mpr (hx (Q.J y) (Q.J_stable_frameSpan v hy))

theorem K_stable_frameSpan_orthogonal (Q : QuaternionicStructure V) (v : V) {x : V}
    (hx : x ∈ (Q.frameSpan v).orthogonal) : Q.K x ∈ (Q.frameSpan v).orthogonal := by
  rw [Submodule.mem_orthogonal'] at hx ⊢
  intro y hy
  rw [Q.K_skew]
  exact neg_eq_zero.mpr (hx (Q.K y) (Q.K_stable_frameSpan v hy))

end QuaternionicStructure
end QuaternionicSymmetry
