import Mathlib.Geometry.Manifold.GroupLieAlgebra
import Mathlib.Geometry.Manifold.LocalDiffeomorph
import Mathlib.Analysis.Complex.Basic

/-! Differential naturality of the actual left-invariant vector fields under
a holomorphic group homomorphism. This is the first internal step toward
bracket transport; no Lie-bracket preservation is assumed. -/

namespace QuaternionicSymmetry.SmoothLieGroupEquivDerivativeBracket

open scoped Manifold ContDiff
noncomputable section

variable {V G H : Type*} [NormedAddCommGroup V] [NormedSpace ℂ V]
  [TopologicalSpace G] [TopologicalSpace H]
  [ChartedSpace V G] [ChartedSpace V H] [Group G] [Group H]
  [LieGroup 𝓘(ℂ,V) ∞ G] [LieGroup 𝓘(ℂ,V) ∞ H]

/-- A smooth group homomorphism sends the genuine invariant vector field
generated by `v` to the invariant field generated by its identity
differential. -/
theorem mfderiv_mulInvariantVectorField
    (f : G → H) (hf : ContMDiff 𝓘(ℂ,V) 𝓘(ℂ,V) ∞ f)
    (hOne : f 1 = 1) (hMul : ∀ g x, f (g*x) = f g * f x)
    (g : G) (v : GroupLieAlgebra 𝓘(ℂ,V) G) :
    (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) f g)
      (mulInvariantVectorField v g) =
    mulInvariantVectorField
      ((mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) f 1) v) (f g) := by
  have hNonzero : (∞ : WithTop ℕ∞) ≠ 0 := by simp
  have hMulG : ContMDiff 𝓘(ℂ,V) 𝓘(ℂ,V) ∞
      (fun x : G => g*x) := contMDiff_mul_left
  have hMulH : ContMDiff 𝓘(ℂ,V) 𝓘(ℂ,V) ∞
      (fun y : H => f g*y) := contMDiff_mul_left
  have hLeft :
      mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) (fun x : G => f (g*x)) 1 =
        (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) f g).comp
          (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) (fun x : G => g*x) 1) := by
    have hComp := mfderiv_comp (1 : G)
      (hf.mdifferentiable hNonzero (g*1))
      (hMulG.mdifferentiable hNonzero (1 : G))
    rw [mul_one] at hComp
    exact hComp
  have hRight :
      mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) (fun x : G => f g * f x) 1 =
        (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) (fun y : H => f g*y) 1).comp
          (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) f 1) := by
    have hComp := mfderiv_comp (1 : G)
      (hMulH.mdifferentiable hNonzero (f 1))
      (hf.mdifferentiable hNonzero (1 : G))
    rw [hOne] at hComp
    exact hComp
  have hEq : (fun x : G => f (g*x)) = (fun x : G => f g * f x) := by
    funext x
    exact hMul g x
  change (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) f g)
      ((mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) (fun x : G => g*x) 1) v) =
    (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) (fun y : H => f g*y) 1)
      ((mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) f 1) v)
  change ((mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) f g).comp
      (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) (fun x : G => g*x) 1)) v =
    ((mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) (fun y : H => f g*y) 1).comp
      (mfderiv 𝓘(ℂ,V) 𝓘(ℂ,V) f 1)) v
  rw [← hLeft, ← hRight, hEq]
  rfl

end
end QuaternionicSymmetry.SmoothLieGroupEquivDerivativeBracket
